// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiZkteco.Models;

namespace WebApiZkteco.Migrations
{
    [DbContext(typeof(ZkContext))]
    partial class ZkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiZkteco.Models.User", b =>
                {
                    b.Property<string>("sUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("iFaceIndex")
                        .HasColumnType("int");

                    b.Property<int>("iFaceLen")
                        .HasColumnType("int");

                    b.Property<int>("iFingerFlag")
                        .HasColumnType("int");

                    b.Property<int>("iFingerLen")
                        .HasColumnType("int");

                    b.Property<int>("iPrivilege")
                        .HasColumnType("int");

                    b.Property<int>("idwFingerIndex")
                        .HasColumnType("int");

                    b.Property<string>("sFaceData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sFingerData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sUserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApiZkteco.Models.UserPending", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("activeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("usersUserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("usersUserID");

                    b.ToTable("UserPendings");
                });

            modelBuilder.Entity("WebApiZkteco.Models.UserPending", b =>
                {
                    b.HasOne("WebApiZkteco.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("usersUserID");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
